name: SonarCloud analysis

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Compiler le projet
        run: mvn clean compile   # Commande adaptée à votre projet

      - name: Analyse avec SonarCloud
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=3npC0nf1g_calculator-cucumber-2025
            -Dsonar.organization=3npc0nf1g
            -Dsonar.scm.provider=git
            -Dsonar.java.binaries=target/classes  # Chemin vers les classes compilées
          projectBaseDir: .
