name: SonarCloud analysis

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Analyser avec Maven et SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar \
             -Dsonar.projectKey=3npC0nf1g_calculator-cucumber-2025 \
             -Dsonar.organization=3npc0nf1g
